# Utilizar una imagen base de Node.js
FROM node:18

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios para instalar las dependencias
COPY package.json package-lock.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto 8080
EXPOSE 8080

# Comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev"]

